Add Store Cog, Inventory Tables/Logic, Inventory Command
DiscordValley/TheValley pull request #51
Opened 2020-09-18 02:48 UTC by ferociouskyle

- Adding Sell Cog (Not finished, wanted to baseline though)
- Added inventories, items model to allow sell/buy/item query to work
- Modified game/player to start working with new tables.
    - Queries are not 100% done, just wanted to baseline.

2020-09-22 13:25 UTC, makupi requested changes
Okay, way more comments than I thought there would be - not bad overall, a couple bugs from what I can tell and a few things are more for the sake of consistency rather than anything.

2020-09-22 13:25 UTC, makupi commented on bot/database/models/inventories.py
> +    item_id = db.Column(db.BIGINT)  # Will be ForeignKey of item.id, doesn't exist yet
Since you have an items table as well this could be a ForeignKey couldn't it?

2020-09-22 13:25 UTC, makupi commented on bot/database/models/items.py
> +    item_id = db.Column(db.BIGINT)
`item_id` on `Item`? I suppose this is wrong - the `Item` already has `Item.id` which will be referred to by other models as `item_id`

2020-09-22 13:25 UTC, makupi commented on bot/database/models/items.py
> +    creation_id = db.Column(db.Integer)
IDs should be `BIGINT`

2020-09-22 13:25 UTC, makupi commented on bot/game/player.py
> +            await InventoryModel.query.where(InventoryModel.id == player_id)
I think this is the same mistake I did, shouldn't this be `InventoryModel.player_id` instead of using the Inventories **id**?

2020-09-22 13:25 UTC, makupi commented on bot/game/player.py
> +            .where(item_id=item_id)
`.where(item_id=item_id)` I think this is wrong? Should probably be `InventoryModel.item_id == item_id` right?

2020-09-22 13:25 UTC, makupi commented on bot/game/player.py
> +            await ItemModel.query.where(ItemModel.item_id == item_id)
This is the issue from the model again, `item_id` should be the `id` of the model, therefore you can simply do `ItemModel.get(item_id)` iirc.

2020-09-22 13:25 UTC, makupi commented on bot/cogs/sell.py
> +class Sell(commands.Cog):
I'm assuming this cog will probably be for selling AND buying, right? Then it should probably be something like "Market" or "Shop" (some for the filename)

2020-09-22 13:25 UTC, makupi commented on bot/cogs/sell.py
> +        itemObj = await Player.item(item_id=item)
`itemObj` python uses snake_case for variable names! Aren't you using PyCharm? Thought this gets flagged as an "error"

2020-09-22 13:25 UTC, makupi commented on bot/cogs/sell.py
> +    async def sell(self, ctx, item, quantity):
Commands should have proper converters (typehints) avoids having to use int() below e.g.
And since you want to accept both item ID and NAME you will need some form of conversion, ideally you'd write a custom converter for this or something like that, for now I'd just make it ID only (since that's what you're doing below)
```py
async def sell(self, ctx, item: int, quantity: int):
```

2020-09-22 13:25 UTC, makupi commented on bot/cogs/sell.py
> +                description='Success! You sold `{}` of `{}`'.format(quantityNum, item),
Not *that* important but for the sake consistency please use f-strings like e.g.:
```py
description=f"Success! You sold {quantity} of {item}"
```

2020-10-01 04:37 UTC, ferociouskyle commented on bot/database/models/items.py
> +    item_id = db.Column(db.BIGINT)
Fixed.

2020-10-01 04:37 UTC, ferociouskyle commented on bot/database/models/items.py
> +    creation_id = db.Column(db.Integer)
Fixed

2020-10-01 10:05 UTC, makupi requested changes
Few minor things, looks good otherwise.

2020-10-01 10:05 UTC, makupi commented on bot/cogs/store.py
> +        item_obj = await Item.item(name=name)
I think we changed this to `Item.load`?

2020-10-01 10:05 UTC, makupi commented on bot/game/item.py
> +        item_obj = await ItemModel.query.where(ItemModel.name == name).gino.first()
As I briefly mentioned, this should probably follow a similar pattern as `Player.load` does, as in, creating a `Item` object and having a `db_object` flag to optionally also return the database object.

2020-10-01 10:05 UTC, makupi commented on bot/game/player.py
> +    async def sell(cls, player_obj, item_obj, inv_obj, quantity: int):
Return type hint missing

2020-10-01 13:47 UTC, ferociouskyle commented on bot/cogs/store.py
> +        item_obj = await Item.item(name=name)
Changed in upcoming commit.

2020-10-10 16:17 UTC, makupi commented
- Add functional Store Cog with Buy/Sell and store commands
- Add Inventory tables
- Add Inventory logic and utility functions for inventory access
- Add basic inventory command

2020-10-10 16:19 UTC, makupi approved these changes
This should be done IMO. @ferociouskyle and @TheCatster should take a look as well maybe.

2020-10-10 16:26 UTC, TheCatster approved these changes
Totally fine with me. Let's merge this jaunt.

2020-10-11 03:26 UTC, merged